### PR TITLE
Issue #691 - improvement to build script: if docker is available, the…

### PR DESCRIPTION
**Pull request by mbert**
Changes to the build script and the build instructions:

- if docker is available, the whole process is performed in docker containers, no need to install further build dependencies on the build host
- if docker is not available, perform some minimal checking on the build dependencies on the host
- implement early fail error handling
- changed the build instructions accordingly

This PR should not make any changes to existing build environments necessary.

### CODE REVIEW

**Comment by petkivim** [comment]
Hi @mbert 

Thank you for your contribution! Before approving it we would need to have the NIIS Contributor License Agreement (CLA) document signed by you. More information about the NIIS CLA and instructions for signing and delivering it can be found at:

https://github.com/nordic-institute/X-Road-development/#contributor-license-agreement

Best regards,
Petteri

**Comment by mbert** [comment]
Can. Unfortunately I am under immense time pressure at the moment (I just squeezed this PR in during my breakfast), and I won't be able to read the document on e-signatures. Is there a quick and simple way? Maybe print out the agreement, sign it, scan it in and send it to some email address?

Sorry to bother you with this, but I really need to move on now.

**Comment by mbert** [comment]
Otherwise I'm totally fine if you take my change, commit it under your own name (may mention me in the commit message) and submit the change, if that's easier for you. I am really not that important :)

**Comment by petkivim** [comment]
The easiest way to proceed with the CLA is to print it out, signg manually and sent to NIIS by post:

```
MTÜ Nordic Institute for Interoperability Solutions
Hobujaama 4
10151 Tallinn
Estonia
```

The evaluation of the pull request will be added to our backlog, and implemented during the upcoming sprints. In other words, the process of reviewing the pull request will take some time in any case, and the CLA probably arrives before it.

**Comment by mbert** [comment]
To be honest this procedure isn't exactly going to encourage a vast community to contribute ;)
You might want to take a look at the way the CNCF are doing this.

Nevertheless, printed, signed, will send this out the coming days.

**Comment by petkivim** [comment]
Thanks! Yes, I know that the process could be more straight forward. Since NIIS is an Estonian organisation, we must have the CLA and its signature in the format that's required by Estonian legislation or otherwise it has no legal value. Fortunately, you only need to submit the CLA once and it covers all you future contributions too.

**Comment by petkivim** [comment]
Hi @mbert

We have reviewed your pull request. Unfortunately, we have decided to reject it, because the current implementation does not serve different needs that X-Road developers may have. For example, the containers that are used to compile the code and build the installation packages are removed after every run. It means that all the dependencies must be downloaded every time when the code is compiled which increases the total build time and adds overhead. Also, developers may prefer to do the build locally on the host even if Docker is installed. 

We agree that doing the whole build process using Docker is something that should be supported. However, the support should be implemented in a more flexible and configurable manner that enables developers to choose between available alternatives. Therefore, we will create a new backlog item about implementing Docker support for the build process and implement it by ourself. 

Thank you for the CLA. We have received it and it's valid for any future contributions.

Best regards,
Petteri

**Comment by mbert** [comment]
I understand where you're coming from. I have amended my commit, and I think it can now cater for what you need. 
I'll open a new PR for it.

**Pull request closed without merging**
