### PR TITLE
Update cache before install required packages

### LINKED ISSUE #186: Problem running ansible xroad-ca in a clean machine
### Issue

I am facing an error when trying to install the role `xroad-ca` in a clean machine from GCP. This is because the fresh machine GCP comes with outdated repositories. 

### How to reproduce
Try to run the ansible script on any fresh machine from GCP

### Expected Result
The script should run without problems

### Actual Result
```
failed: [ca.xvia.com.br] (item=nginx-light) => {"ansible_loop_var": "item", "changed": false, "item": "nginx-light", "msg": "No package matching 'nginx-light' is available"}
```

### Possible solution
Force apt to update the packages before trying to install the new packages.

```yaml
- name: Update all packages to the latest version
  apt:
    update_cache: yes
```

### PR DESCRIPTION
**Pull request by nanndoj**
Fixes #186 a d #232

### CODE REVIEW

**Comment by petkivim** [comment]
Hi @nanndoj 

Thank you for your contribution! Before approving it we would need to have the NIIS Contributor License Agreement (CLA) document signed by you. More information about the NIIS CLA and instructions for signing and delivering it can be found at:

https://github.com/nordic-institute/X-Road-development/#contributor-license-agreement

Best regards,
Petteri

**Comment by nanndoj** [comment]
Hi @petkivim,

Thanks, I’ll Send the letter on Monday. I think would be nice to help on the project. Meanwhile feel free to reject this pull request. I will open a ticket instead 😉

**Comment by petkivim** [comment]
Hi @nanndoj 

Excellent, it's great to have you as a contributor! :smile:

I reopen this pull request and it'll be approved once we receive the signed CLA from you. 

Best regards,
Petteri

**Comment by iluwatar** [comment]
ok to test

**Comment by iluwatar** [comment]
test this please

**Comment by iluwatar** [comment]
add to whitelist

**Pull request merged**
