### PR TITLE
Changes to the ansible playbook for a security server cluster setup to handle changes in X-Road version 6.24.0:

### PR DESCRIPTION
**Pull request by bthj**
- add serverconf_admin role to the separate serverconf database instance
- remove references to xroad-jetty
- exclude /etc/xroad/jetty in the initial configuration sync from slaves (due to file permission errors)

### CODE REVIEW

**Comment by petkivim** [comment]
Hi @bthj 

Thank you for your contribution! Before approving it we would need to have the NIIS Contributor License Agreement (CLA) document signed by you. More information about the NIIS CLA and instructions for signing and delivering it can be found at:

https://github.com/nordic-institute/X-Road-development/#contributor-license-agreement

Best regards,
Petteri

**Comment by bthj** [comment]
Hi @petkivim 

Last Friday I sent the CLA to the NIIS info email address, with a QES (previously I had sent it with an AES).

Best regards
/Björn

**Comment by petkivim** [comment]
Hi @bthj 

Thanks for the update! The CLA issue is being handled through our service desk so let's continue the process there.

Best regards,
Petteri

**Review by iluwatar — CHANGES_REQUESTED** [review]
@bthj many thanks for your interest to work alongside us to improve the open-source X-Road solution!

The essence of the proposed change, the addition to `ansible/ss_cluster/group_vars/all` is unfortunately a duplicate. The option already exists in the same file. For this reason, we have to reject this pull request. 

In case you are interested to submit only the documentation-related changes, please take a look at the review comments and send another pull request.

**Pull request closed without merging**
