### PR TITLE
XRDDEV-1259-and-1270

### PR DESCRIPTION
**Pull request by carohauta**
Add new permissions for creating/viewing/editing/revoking API-keys (for admins). Allow users with observer role to view API-keys.

JIRA (frontend): https://jira.niis.org/browse/XRDDEV-1259
JIRA (backend): https://jira.niis.org/browse/XRDDEV-1270

### CODE REVIEW

**Comment by carohauta** [comment]
Some (possibly) random npm conflict error while building. Restarted the Jenkins build: https://jenkins.niis.org/job/pr-build-pipeline/1434/

**Review by raits — CHANGES_REQUESTED** [review]
I think this method in [ApiKey.vue@86:91](https://github.com/nordic-institute/X-Road/blob/59ede09dd6e754f4bba9b471f0a2b6e79b5d3eb7/src/proxy-ui-api/frontend/src/views/KeysAndCertificates/ApiKey/ApiKey.vue#L86-L91) should also check if the user has the "VIEW_API_KEYS" permission before running, to be in sync with the backend permissions:
```
    loadKeys(): void {
      api
        .get<ApiKey[]>('/api-keys')
        .then((resp) => (this.apiKeys = resp.data))
        .catch((error) => this.$store.dispatch('showError', error));
    },
```

**Review by jansu76 — APPROVED** [review]
Backend looks good.

**Review by raits — APPROVED** [review]

**Comment by raits** [comment]
Looks good to me.

**Pull request merged**
