### PR TITLE
Fix date filter

### PR DESCRIPTION
**Pull request by yamatokataoka**
Fix date filter as getMonth() returns 0-11.

### CODE REVIEW

**Comment by petkivim** [comment]
Hi @yamatokataoka 

Thank you for your contribution! Before approving it we would need to have the NIIS Contributor License Agreement (CLA) document signed by you. More information about the NIIS CLA and instructions for signing and delivering it can be found at:

https://github.com/nordic-institute/X-Road-development/#contributor-license-agreement

Best regards,
Petteri

**Comment by yamatokataoka** [comment]
hi @petkivim 
sorry for late respose but I sent the CLA a week ago.

Best regards,
Yamato Kataoka

**Comment by petkivim** [comment]
Hi @yamatokataoka 

Sorry for a slow reply. We needed to validate a few things regarding the digital signature, and unfortunately, we cannot approve the signature due a couple of validation issues. I have sent you more detailed information about the issues from our JIRA.

Unfortunately, this means that you should print the CLA, sign it by hand and sent it to NIIS by post:

```
MTÜ Nordic Institute for Interoperability Solutions
Hobujaama 4
10151 Tallin
```

Best regards,
Petteri

**Comment by Riippi** [comment]
This is now fixed in https://github.com/nordic-institute/X-Road/pull/544
so I will close this PR.

**Pull request closed without merging**
