### PR TITLE
feat: generate sidecar grpc tls keys

### PR DESCRIPTION
**Pull request by justasnortal**
Refs: XRDDEV-2517

### CODE REVIEW

**Review by ricardas-buc — APPROVED** [review]

**Comment by AndriMar** [comment]
@justasnortal Could it be that this is missing for the secondary container?
The secondary entrypoint is not sourcing the _entrypoint_common.sh like the primary entrypoint is doing.
We are getting this error on secondary
`2023-12-28T13:13:22.386Z ERROR [xroad-proxy] [main] o.n.x.c.rpc.RpcCredentialsConfigurer - Failed to read gRPC keystore.
December 28, 2023 at 13:13 (UTC)	java.nio.file.NoSuchFileException: /var/run/xroad/xroad-grpc-internal-keystore.p12`

**Comment by justasnortal** [comment]
@AndriMar thanks for pointing that out, it is indeed missing in the secondary containers.

**Comment by petkivim** [comment]
@AndriMar New versions of the `niis/xroad-security-server-sidecar` images containing a fix to the problem have been published to Docker Hub.

**Comment by AndriMar** [comment]
@petkivim great thank you!

**Pull request merged**
