### PR TITLE
chore: fix an issue where cpuLoad returns NaN

### PR DESCRIPTION
**Pull request by ricardas-buc**
fix an issue where cpuLoad returns NaN which leads to AntiDos protection being triggerred.

This behavior was noted in JDK17 on MacOS.

### CODE REVIEW

**Comment by justasnortal** [comment]
[rerun-ci]

**Comment by justasnortal** [comment]
[rerun-ci]

**Review by justasnortal — APPROVED** [review]

**Comment by ovidijusnortal** [comment]
[rerun-ci]

**Comment by ovidijusnortal** [comment]
[rerun-ci]

**Pull request merged**
