### PR TITLE
feat: XRDDEV-2728 Complement - Adding Spanish language support

### PR DESCRIPTION
**Pull request by figueroarvictor**
This Pull Request adds support for the Spanish language in the X-Road UI. The following changes were made:
- Added `es.json` localization files for `central-server`, `security-server`, and `shared-ui`.
- Updated the `i18n.ts` files to include Spanish as a supported language.
- Updated the `index.ts` file in `shared-ui` to load Spanish localization.

Ref: XRDDEV-2787

### CODE REVIEW

**Comment by ovidijusnortal** [comment]
@figueroarvictor 
Hi, we extracted some additional common translations from Security server admin UI and Central server UI into shared-ui module to avoid translating same thing multiple times(https://github.com/nordic-institute/X-Road/pull/2464). 
Can you check your PR and match up your translations with new versions of en locale files? at least one in shared-ui module

**Comment by figueroarvictor** [comment]
@ovidijusnortal I am seeing that a language file for Estonia has also been added, so I will also update the scripts to incorporate it.

**Comment by figueroarvictor** [comment]
@ovidijusnortal, 
Hi,  I've updated Spanish translations in all modules (shared-ui, central-server, and security-server) and added Estonian support in shared-ui.

**Review by ovidijusnortal — APPROVED** [review]

**Comment by ovidijusnortal** [comment]
@figueroarvictor 
Hey,
looks good. Only left to wait for  Estonian translations updated.

**Comment by raits** [comment]
@figueroarvictor unfortunately, we needed to add a few new fields related to diagnostics: https://github.com/nordic-institute/X-Road/pull/2472/files#diff-c667a377a7d520d463b41c9734653e52d2ca512b236152a7dcf8d6bab0dfd7f8

Could you please update the Spanish translation to include these new fields as well?

**Comment by figueroarvictor** [comment]
Hi Raido,

Yes; I just need a few hours for push the updates needed.
Regards,

**Comment by raits** [comment]
> Hi Raido, Yes; I just need a few hours for push the updates needed. Regards

Thanks!

**Comment by figueroarvictor** [comment]
Hi @raits,

Changes made in Security Server es.json file.

Regards,

**Comment by raits** [comment]
> Hi @raits,
> 
> Changes made in Security Server es.json file.
> 
> Regards,

Thank you!

**Pull request merged**
