### PR TITLE
XRDDEV-1619 e2etest development fixes

### PR DESCRIPTION
**Pull request by olliru**
Fixes to development e2e test failures

### CODE REVIEW

**Review by TJaakkola — APPROVED** [review]

**Comment by TJaakkola** [comment]
Ok to merge after successfull build

**Comment by jhyoty** [comment]
Merging should wait until 7.0 is merged back to develop

**Comment by TJaakkola** [comment]
> Merging should wait until 7.0 is merged back to develop

**Review by iluwatar — CHANGES_REQUESTED** [review]
There are conflicts preventing the merge.

**Comment by iluwatar** [comment]
Since the changes here concern X-Road 6 and the develop-branch is already at V7, we won't merge this. Instead, the changes are left in the branch and documented in the JIRA ticket and Confluence.

**Pull request closed without merging**
